services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres
    networks:
      - social-media-net
  migrate:
    image: migrate/migrate:latest
    container_name: migrate
    volumes:
      - ./cmd/migrate/migrations:/migrations # Mount migration files
    depends_on:
      - postgres
    networks:
      - social-media-net
    profiles: ["tools"]
  backend:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.dev

    container_name: backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/tmp
    networks:
      - social-media-net

volumes:
  postgres_data:

networks:
  social-media-net:
    driver: bridge
